sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.2
- 2.3
- 2.4.1
- ruby-head
before_install: gem install bundler -v 1.14.6
before_script:
- export CODECLIMATE_REPO_TOKEN=5a1c95e9c71ba0cd4c1a5aef955b7fe0cb4958d3b78e6b94c6a62d0653136ea0
- export CI=true
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter
branches:
  only:
  - master
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  slack:
    secure: NQ3WpJRRXxBaxUanRr0GzTXaBqoj1dQagkH3EqgLAF68+1DabWMhfVDRXRGRvBOoZtY7WrqWViv5nQ4y6kqgrsXdc6aZwgiGZj8kFPdYdxTDQKnDnL3TMJkvMgQlmbADEuyCz7DsM6eUzkomtVcJG/ZREBoMqzRwkgSNu3QCi183RYaCiMTFmAu2P4XSuX3ypVQrLxKmUdlPCzj2eww6Kr4ob9a6B9CwLrbkSv4W8UpsH6ue6qEGjyglj+dfHowzn9UfCkHb7wPHXvcjD25xVNxsNgeZ/htQojmxI5sb1UmH3Q+8faHDh+ckKfnq+HkZXY/9ekSkQVtpbxwxMvghg0NjNWWnx+n3zwECMa3YxAK1KuAAyafkGJ90htdVf4SJgsSrLFfP3Dh7tCksa+/BpwG1nPt3rrLu+Y0cBsXyH/9tM4qkmLIwBiQJ8H9GmZBn6kRDWKEv0uxaoVxSyjCc+CIVpOdd3bxhJ1b46siP3pVzVEch60dhPpb1hp6KEHBRlZtibB94zIjRs4Sw4AJwTZuthYfabhotxp29tJox8xnMo870i0FtV3ptdb+Jn+JVnpA5vvp3mktgZALGQd32Rk0JoluxCsNw5IC0cIECNT4R2L6R/vF1TvajlPGblZiYruaqqXDmuCZrBu8L4JK32Jdv+KTm2zFEmBs/dWBDDuY=
